services:
  app:
    ports:
      - 80:80   
      - 5678:5678
  db:    
    ports:
      - 5432:5432
  dbtest:
    ports:
      - 5433:5432
  
networks:
  traefik-public:
    external: false