name: Build and Deploy code
on: [push, pull_request]
jobs:
  job1:
    # env:
    #   NODE_ENV: development
    #   DB_HOST: localhost
    #   DB_PORT: 5432
    #   DB_USER: postgres
    #   DB_PASSWORD: postgres
    #   DB_NAME: fastapi
    #   SECRET_KEY: c0f1cd4babc2eecd335c47a0c137f9fa61986710aa4ad70e8dab6f4945af2ac2

    # # Service containers to run with `runner-job`
    # services:
    #   # Label used to access the service container
    #   postgres:
    #     # Docker Hub image
    #     image: postgres
    #     # Provide the password for postgres
    #     env:
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: fastapi_test
    #     # Set health checks to wait until postgres has started
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5
    #     ports:
    #       # Maps tcp port 5432 on service container to the host
    #       - 5432:5432

    runs-on: ubuntu-latest
    steps:
      - name: Pulling git repo
        uses: actions/checkout@v3      
      - name: docker-compose up --build
        uses: sudo-bot/action-docker-compose@latest
        with:
            # https://docs.docker.com/compose/reference/overview/
            cli-args: "up --build"
      - name: docker-compose exec app pytest
        uses: sudo-bot/action-docker-compose@latest
        with:
            # https://docs.docker.com/compose/reference/overview/
            cli-args: "exec app pytest"
      - name: docker-compose down
        uses: sudo-bot/action-docker-compose@latest
        with:
            # https://docs.docker.com/compose/reference/overview/
            cli-args: "down"
      # - name: docker-compose up
      #   run: docker-compose up -d
      #   env:
      #     COMPOSE_INTERACTIVE_NO_CLI: 1
      # - name: Check running containers
      #   run: docker-compose ps -a
      # - name: Check logs
      #   run: docker-compose logs app
      # - name: Test with pytest
      #   env:
      #     COMPOSE_INTERACTIVE_NO_CLI: 1
      #   run: docker-compose exec app pytest


      # - name: Install Python v3.10
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10' 
      # - name: Update pip
      #   run: python -m pip install --upgrade pip
      # - name: Install all dependencies
      #   run: pip install -r requirements.txt
      # - name: Test with pytest
      #   run: |
      #     pip install pytest
      #     pytest
      # -
      #   name: Checkout
      #   uses: actions/checkout@v3
      # -
      #   name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-docker