name: Test and Build code
on: [workflow_dispatch]
jobs:  
  # test:
  #   env:
  #     DB_USER: ${{ secrets.DB_USER }}
  #     POSTGRES_USER: ${{ secrets.DB_USER }}
  #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  #     POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
  #     SECRET_KEY: ${{ secrets.SECRET_KEY }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - 
  #       name: Checkout code
  #       uses: actions/checkout@v3

  #     - 
  #       name: Start services
  #       run: |
  #         docker-compose up -d
  #         docker-compose ps 

  #     - 
  #       name: Run pytest
  #       run: |
  #         docker-compose exec -T app pytest

  #     - 
  #       name: Stop services
  #       run: |
  #         docker-compose down
  # build:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - 
  #       name: Checkout code
  #       uses: actions/checkout@v3
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-docker
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max
  deploy:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - 
        name: Checkout the repo 
        uses: actions/checkout@v2
      - 
        name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
      - 
        name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - 
        name: Deploy with rsync
        run: rsync -avz . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/stegul/code/docker-fastapi/
      - 
        name: Restart Node Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}          
          script: |
            cd /home/stegul/code/docker-fastapi
            docker-compose -f docker-compose.yml up --build -d
            docker-compose -f docker-compose.traefik.yml up  --build -d