name: Build and Deploy code
on: [workflow_dispatch]
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3

      - 
        name: Start services
        run: |
          docker-compose up -d
          docker-compose ps 

      - 
        name: Run pytest
        run: |
          docker-compose exec -T app pytest

      - 
        name: Stop services
        run: |
          docker-compose down
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-docker
          cache-from: type=gha
          cache-to: type=gha,mode=max