name: Test and Build code
on: [workflow_dispatch]
jobs:  
  # test:
  #   env:
  #     DB_USER: ${{ secrets.DB_USER }}
  #     POSTGRES_USER: ${{ secrets.DB_USER }}
  #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  #     POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
  #     SECRET_KEY: ${{ secrets.SECRET_KEY }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - 
  #       name: Checkout code
  #       uses: actions/checkout@v3

  #     - 
  #       name: Start services
  #       run: |
  #         docker-compose up -d
  #         docker-compose ps 

  #     - 
  #       name: Run pytest
  #       run: |
  #         docker-compose exec -T app pytest

  #     - 
  #       name: Stop services
  #       run: |
  #         docker-compose down
  # build:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   steps:
  #     - 
  #       name: Checkout code
  #       uses: actions/checkout@v3
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2
  #     -
  #       name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
  #     -
  #       name: Build and push
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         push: true
  #         tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-docker
  #         cache-from: type=gha
  #         cache-to: type=gha,mode=max
  deploy:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - 
        name: Checkout the repo 
        uses: actions/checkout@v2
      - 
        name: Build image 
        run: docker build -t sample/my-page .
      -
        name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - 
        name: Log in to DO Container Registry 
        run: doctl registry login
      - 
        name: Tag image 
        run:
          docker tag sample/my-page \
          registry.digitalocean.com/stegul/my-sample-page:${{github.event.inputs.version }}
      - 
        name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/stegul/my-sample-page:${{ github.event.inputs.version }}