name: Build and Deploy code
on: [push, pull_request]
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3

      - 
        name: Start services
        run: |
          docker-compose up -d
          docker-compose ps 

      - 
        name: Run pytest
        run: |
          docker-compose exec -T app pytest

      - 
        name: Stop services
        run: |
          docker-compose down
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-docker
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v3
      - 
        name: generate env
        run: |
          export USERNAME=admin
          export PASSWORD=S8D7oPqPZizJ8HX
          export HASHED_PASSWORD=$(openssl passwd -apr1 $PASSWORD)
      - 
        name: Start services docker 2
        run: |
          docker-compose -f docker-compose.traefik.yml up  --build -d
          docker-compose -f docker-compose.yml up --build -d          