name: Build and Deploy code
on: [push, pull_request]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Start services
          run: |
            docker-compose up -d
            docker-compose ps 

        - name: Run pytest
          run: |
            docker-compose exec -T app pytest

        - name: Stop services
          run: |
            docker-compose down
        -
          name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        -
          name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-docker
        - name: Sync
          uses: ms-jpq/sync-dockerhub-readme@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
            repository: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-docker
            readme: "./README.md"